// Facility space categories; max_tiles used for schematic floorplan
export const FACILITY_SPACE = [
  { space: "Cramped", max_tiles: 4, add_cost_gp: 500, enlarge_cost_gp: 250, build_days: 10 },
  { space: "Roomy",   max_tiles: 9, add_cost_gp: 1000, enlarge_cost_gp: 500, build_days: 20 },
  { space: "Vast",    max_tiles: 25, add_cost_gp: 3000, enlarge_cost_gp: 1500, build_days: 40 }
];

export const SPECIAL_BY_LEVEL = [
  { min_level: 5,  max_special: 2 },
  { min_level: 9,  max_special: 4 },
  { min_level: 13, max_special: 5 },
  { min_level: 17, max_special: 6 }
];

export const VALID_ORDERS = ["Craft","Empower","Harvest","Recruit","Research","Trade","None"];
export const ENCLOSURE_THRESHOLD_DEFAULT = 40; // sections needed to consider the Bastion enclosed
// Expanded to ~2× entries. Names now 52; species covers major 5e-playable races.
// Weights are relative (need not sum to 1).

export const HIRELING_NAMES = [
  ["Aelar",0.05],["Borin",0.04],["Cassandra",0.05],["Dorin",0.03],["Elaith",0.04],["Faelar",0.04],
  ["Glim",0.03],["Hilde",0.03],["Ilyana",0.04],["Jorin",0.05],["Kethra",0.05],["Loram",0.03],
  ["Mara",0.04],["Nym",0.04],["Oskar",0.03],["Perrin",0.04],["Quinn",0.03],["Ragnar",0.03],
  ["Seraphina",0.05],["Thorin",0.04],["Ulric",0.04],["Valanthe",0.03],["Wren",0.04],["Xander",0.03],
  ["Yara",0.05],["Zorin",0.04],
  ["Alaric",0.04],["Brina",0.03],["Caelum",0.03],["Daria",0.04],["Edrin",0.03],["Fenra",0.03],
  ["Garrick",0.04],["Helga",0.03],["Isolde",0.04],["Jax",0.03],["Kael",0.04],["Liora",0.04],
  ["Maelis",0.03],["Neris",0.03],["Orrin",0.03],["Petra",0.04],["Riven",0.03],["Sorin",0.04],
  ["Tamsin",0.03],["Ulfgar",0.03],["Vesper",0.03],["Wynne",0.03],["Xara",0.03],["Ysra",0.03],
  ["Zephyr",0.03],["Thalia",0.04],
  ["Arielle",0.04],["Bastian",0.03],["Corin",0.03],["Delara",0.04],["Elrik",0.03],["Fiora",0.03],
  ["Galen",0.04],["Hester",0.03],["Isarn",0.04],["Jorah",0.03],["Kieran",0.04],["Lunara",0.04],
  ["Marek",0.03],["Nyssa",0.03],["Oberon",0.03],["Phaedra",0.04],["Quillon",0.03],["Rhoswen",0.04],
  ["Sylas",0.03],["Torin",0.03],["Urien",0.03],["Valken",0.03],["Willow",0.03],["Xyra",0.03],
  ["Yorick",0.03],["Zayra",0.03],
  ["Aedric",0.03],["Brynn",0.03],["Cassian",0.03],["Daelia",0.04],["Emric",0.03],["Fendrel",0.03],
  ["Gracen",0.03],["Hadric",0.03],["Ilara",0.03],["Jaspar",0.03],["Kallista",0.03],["Lucien",0.03],
  ["Marwen",0.03],["Niall",0.03],["Orla",0.03],["Phineas",0.03],["Quen",0.03],["Ravena",0.03],
  ["Selric",0.03],["Tavian",0.03],["Umara",0.03],["Virel",0.03],["Wystan",0.03],["Xavian",0.03],
  ["Ysolde",0.03],["Zorion",0.03]
];


// Broad coverage of 5e playable races/subraces across PHB, supplements, Eberron, Ravnica, Theros,
// Strixhaven, Witchlight, Mordenkainen Presents, and Spelljammer. Adjust mix as desired.
export const HIRELING_SPECIES = [
  ["Human",0.14],["Elf",0.08],["Dwarf",0.07],["Halfling",0.05],["Gnome",0.05],
  ["Half-Elf",0.07],["Half-Orc",0.05],["Tiefling",0.05],["Dragonborn",0.05],
  ["Aasimar",0.03],["Goliath",0.025],["Tabaxi",0.02],["Kenku",0.02],["Firbolg",0.02],
  ["Triton",0.02],["Lizardfolk",0.02],["Tortle",0.015],["Goblin",0.02],["Hobgoblin",0.015],
  ["Bugbear",0.015],["Kobold",0.02],["Yuan-ti Pureblood",0.01],["Aarakocra",0.015],
  ["Genasi (Air)",0.01],["Genasi (Earth)",0.01],["Genasi (Fire)",0.01],["Genasi (Water)",0.01],
  ["Githyanki",0.01],["Githzerai",0.01],
  ["Warforged",0.015],["Kalashtar",0.01],["Shifter",0.012],["Changeling",0.012],
  ["Leonin",0.01],["Satyr",0.012],["Minotaur",0.01],["Centaur",0.01],
  ["Loxodon",0.01],["Vedalken",0.01],["Simic Hybrid",0.01],
  ["Owlin",0.01],["Harengon",0.012],["Fairy",0.012],
  ["Autognome",0.008],["Giff",0.008],["Hadozee",0.008],["Plasmoid",0.008],["Thri-kreen",0.008],
  // Elf lineages (often folded into Elf; kept here for flavor variety)
  ["Eladrin",0.01],["Sea Elf",0.01],["Shadar-kai",0.01]
];

// (Optional) If you also want BASIC_FACILITIES roughly doubled, append neutral, non-special basics:
export const BASIC_FACILITIES = [
  { name: "Bedroom",     default_space: "Cramped", desc: "Personal quarters for rest and privacy." },
  { name: "Dining Room", default_space: "Roomy",   desc: "Common space for meals and gatherings." },
  { name: "Parlor",      default_space: "Cramped", desc: "Comfortable space for informal meetings." },
  { name: "Courtyard",   default_space: "Vast",    desc: "Open outdoor space within the Bastion." },
  { name: "Kitchen",     default_space: "Roomy",   desc: "Meal preparation with implements and storage." },
  { name: "Storage",     default_space: "Roomy",   desc: "Secure area for supplies, tools, and goods." },
  // Added (6 more basics; purely cosmetic/utility so they won’t collide with your specials logic)
  { name: "Guest Room",  default_space: "Cramped", desc: "Simple quarters for visitors." },
  { name: "Study Nook",  default_space: "Cramped", desc: "Quiet alcove for reading and notes." },
  { name: "Bathhouse",   default_space: "Roomy",   desc: "Heated baths and steam for relaxation." },
  { name: "Cellar",      default_space: "Roomy",   desc: "Cool underground space for casks and stores." },
  { name: "Larder",      default_space: "Roomy",   desc: "Pantry with preserved food and ingredients." },
  { name: "Common Room", default_space: "Vast",    desc: "Large gathering hall for residents and guests." }
];

export const SPECIAL_FACILITIES = [
  // Level 5
  ["Arcane Study",5,"Arcane Focus or tool as Spellcasting Focus","Roomy",1,["Craft","Research"]],
  ["Armory",5,"None","Roomy",1,["Trade"]],
  ["Aviary",5,"None","Cramped",1,["Recruit"]],
  ["Barrack",5,"None","Roomy",1,["Recruit"]],
  ["Garden",5,"None","Roomy",1,["Harvest"]],
  ["Library",5,"None","Roomy",1,["Research"]],
  ["Portentorium",5,"None","Roomy",1,["Empower"]],
  ["Sanctuary",5,"Holy Symbol or Druidic Focus","Roomy",1,["Craft","Empower"]],
  ["Storehouse",5,"None","Roomy",1,["Trade"]],
  ["Trapworks",5,"Proficiency with Thieves’ Tools or Sleight of Hand","Roomy",1,["Craft"]],
  ["Workshop",5,"None","Roomy",3,["Craft"]],

  // Level 9
  ["Greenhouse",9,"None","Roomy",1,["Harvest"]],
  ["Inn",9,"None","Vast",2,["Empower"]],
  ["Laboratory",9,"None","Roomy",1,["Craft"]],
  ["Prison",9,"None","Roomy",1,["Research"]],
  ["Sacristy",9,"Holy Symbol or Druidic Focus","Roomy",1,["Craft","Harvest"]],
  ["Scriptorium",9,"None","Roomy",1,["Craft","Research"]],
  ["Stable",9,"None","Roomy",1,["Trade","Recruit"]],
  ["Training Area",9,"None","Vast",4,["Empower"]],
  ["Trophy Room",9,"None","Roomy",1,["Research"]],
  ["Warlord’s Honor Hall",9,"Access to Weapon Mastery for two or more weapons","Roomy",1,["Empower"]],

  // Level 13
  ["Archive",13,"None","Roomy",1,["Research"]],
  ["Dungeon",13,"None","Roomy",1,["Trade"]],
  ["Meditation Chamber",13,"None","Cramped",1,["Empower"]],
  ["Menagerie",13,"None","Vast",2,["Recruit","Harvest"]],
  ["Mobile Bastion Engine",13,"None","Roomy",2,["Move"]],
  ["Observatory",13,"Spellcasting Focus","Roomy",1,["Empower","Research"]],
  ["Reliquary",13,"Holy Symbol or Druidic Focus","Cramped",1,["Harvest","Research"]],
  ["Scrying Chamber",13,"Spellcasting Focus (Arcane/Druidic/Holy Symbol)","Roomy",1,["Research"]],
  ["Temple",13,"None","Roomy",1,["Recruit"]],

  // Level 17
  ["Sanctum",17,"Holy Symbol or Druidic Focus","Roomy",4,["Empower"]],
  ["Demiplane",17,"Arcane Focus or tool as Spellcasting Focus","Vast",1,["Empower","Research"]],
  ["Guildhall",17,"Expertise in a skill","Vast",1,["Recruit","Trade"]],
  ["War Room",17,"Fighting Style or Unarmored Defense","Vast",2,["Recruit","Research"]]
].map(([name,min_level,prereq,space,hirelings,orders]) => ({
  name, min_level, prereq, space, hirelings, orders
}));

export const BASTION_DESCRIPTIONS = [
  "A weathered stone fortress built into a cliffside, with waves crashing against its base.",
  "A sprawling timber hall surrounded by wildflower meadows, its roof crowned with carved wooden beasts.",
  "A towering obsidian spire that reflects the night sky, even under daylight.",
  "A low, moss-covered keep nestled deep in an ancient forest, its walls blending into the greenery.",
  "A grand marble villa, ringed by columns and open-air courtyards, bathed in perpetual sunlight.",
  "A squat, iron-plated bastion that hums faintly, as if alive with hidden mechanisms.",
  "A crescent-shaped castle perched atop a waterfall, its outer wall constantly wreathed in mist.",
  "A labyrinthine warren of interconnected stone tunnels beneath a lonely hill.",
  "A shimmering crystalline fortress that changes color with the weather.",
  "A floating citadel tethered to the ground by massive chains.",
  "A cluster of windmills built into tall sea cliffs, each with carved runes along its blades.",
  "A sprawling desert caravanserai with shaded courtyards and high walls of sun-baked clay.",
  "A sprawling wooden palisade around a central hearth-fire that never goes out.",
  "A towering basalt citadel split by a glowing fissure of molten rock.",
  "A cliffside monastery accessible only by rope bridges and carved steps.",
  "A squat keep atop a grassy hill, ringed by concentric earthen ramparts.",
  "A fortress half-swallowed by a massive, ancient tree whose roots and branches reinforce its walls.",
  "A sprawling arcane campus with domed observatories and floating lanterns.",
  "A weather-beaten lighthouse that also serves as a watchtower for miles around.",
  "A stronghold carved into the bones of an immense, long-dead leviathan.",
  "A mist-shrouded watchtower built at the meeting point of three rivers.",
  "A gleaming bastion whose walls are inlaid with gold and silver filigree.",
  "A sprawling mountain fortress reached by a single narrow causeway.",
  "A hollowed-out glacier fortress glowing with inner blue light.",
  "A lonely tower on a salt flat, surrounded by strange crystalline growths.",
  "A fortified bridge that spans an impossibly deep chasm.",
  "A squat bastion built from black volcanic rock, always warm to the touch.",
  "A seaside fort whose walls are made of massive, fossilized coral.",
  "A series of stone terraces carved into a cliff, each hosting gardens and dwellings.",
  "A massive fortress carved from a single colossal geode.",
  "A tall, ivy-draped tower whose windows always glow warmly at night.",
  "A fortress that appears partially transparent, its halls filled with ghostly echoes.",
  "A star-shaped citadel surrounded by a shimmering moat of magical light.",
  "A hilltop fortress whose banners are enchanted to always billow in a phantom wind.",
  "A heavily fortified harbor bastion with towers shaped like ship prows.",
  "A sprawling complex of towers and skybridges suspended between mountain peaks.",
  "A bastion built into the trunk of a colossal petrified tree.",
  "A snow-covered stone keep with roaring fires visible from the gates.",
  "A wide, squat fortress surrounded by an endless field of carved standing stones.",
  "A fortress built entirely from massive interlocking brass plates.",
  "A narrow, spiraling tower that seems to defy gravity.",
  "A hidden fortress accessible only through a waterfall curtain.",
  "A keep whose walls are engraved with a map of the surrounding lands.",
  "A bastion surrounded by enchanted orchards that bear fruit year-round.",
  "A floating bastion that drifts slowly across the landscape.",
  "A towering fortress of ice and steel that resists all heat.",
  "A sprawling bastion carved into the walls of a canyon.",
  "A keep surrounded by a moat filled not with water, but glowing arcane energy.",
  "A low-walled bastion with hundreds of colorful banners hanging from poles.",
  "A sprawling villa with mirrored walls that reflect illusions of far-off places.",
  "A towering bastion topped with a massive, ever-burning brazier.",
  "A squat fortress built around an ancient stone monolith.",
  "A cliffside bastion whose balconies overlook roaring waves below.",
  "A fortress whose central tower holds an enormous, slowly turning astrolabe.",
  "A bastion whose gates are shaped like the open jaws of a great beast.",
  "A keep encased entirely in thick, twisting vines of living wood.",
  "A bastion built on stilts above a vast marshland.",
  "A crumbling ruin that is constantly rebuilding itself through unseen magic.",
  "A gleaming silver tower that sings when the wind passes through it.",
  "A fortress of blackened stone that absorbs all sound nearby.",
  "A squat keep built in the center of a vast hedge maze.",
  "A fortress ringed by colossal statues that watch intruders with shifting eyes.",
  "A bastion built entirely underground, lit by glowing crystal pillars.",
  "A keep whose highest tower is crowned with a massive glass dome.",
  "A bastion of pale stone that seems to glow faintly in moonlight.",
  "A sprawling fortified monastery surrounded by rice paddies.",
  "A high-walled bastion with a single massive gate carved from jade.",
  "A fortress whose ramparts are carved into the likenesses of warriors.",
  "A towering fortress whose roof is a living garden.",
  "A citadel of blue stone that changes shade throughout the day.",
  "A bastion with walls made from gigantic, interlocked seashells.",
  "A keep whose foundation is an ancient, enchanted golem.",
  "A bastion of white marble surrounded by crystal-clear canals.",
  "A fortress shaped like a massive spiral shell.",
  "A tall tower that emits a faint, continuous beam of light into the sky.",
  "A bastion with battlements shaped like dragon wings.",
  "A sprawling cliffside bastion with cascading waterfalls between its tiers.",
  "A keep that hums with the sound of distant bells.",
  "A fortress whose walls are painted with ever-changing murals.",
  "A bastion with massive, rotating windcatchers built into its towers.",
  "A stronghold hidden entirely beneath a shimmering illusory hill.",
  "A bastion whose central courtyard holds a massive, enchanted tree.",
  "A keep whose moat is filled with bioluminescent fish.",
  "A fortress built into the ruins of an ancient temple.",
  "A bastion that constantly smells faintly of incense.",
  "A stronghold made of interwoven branches and roots.",
  "A fortress surrounded by floating stone monoliths.",
  "A keep built atop a colossal turtle that roams slowly across the land.",
  "A bastion carved from solid obsidian, polished to a mirror sheen.",
  "A fortress whose walls bear glowing runes in an unknown language.",
  "A keep that seems larger on the inside than from without.",
  "A bastion whose towers are topped with giant, glittering gemstones.",
  "A fortress surrounded by a moat of slow-moving molten rock.",
  "A keep whose walls are covered in climbing roses that never wither.",
  "A bastion built inside the ribcage of an immense fossilized beast.",
  "A fortress whose halls echo with faint, ancient music.",
  "A keep perched on a knife-thin ridge between two valleys.",
  "A bastion guarded by massive animated statues.",
  "A fortress whose gates are made from petrified dragon bone.",
  "A bastion whose spires are shaped like reaching hands.",
  "A keep hidden within an enormous sand dune.",
  "A bastion perched atop a colossal stone hand rising from the earth."
];

export const BASTION_QUIRKS = [
  "The shadows in this place move slightly at all times, as if cast by a flickering unseen light.",
  "Chairs, tables, and shelves occasionally shuffle a few inches on their own.",
  "Footsteps or spoken words echo longer than normal, giving an impression of grandeur even in smaller chambers.",
  "Tiny glowing mushrooms or vines grow on walls, casting a soft, eerie glow.",
  "An unseen force tidies the space at night, stacking objects neatly or sweeping floors.",
  "At dusk, clouds of fireflies gather around the property, lighting it in a flickering dance of light.",
  "Some corners are ice-cold, while others feel uncomfortably warm without any apparent source.",
  "Hidden under peeling paint or moss, a mural depicts scenes of a lost civilization.",
  "Doors (or gates) swing shut and lock themselves if left unattended for too long.",
  "Wind chimes or bell fragments hidden in rafters make soft music when a breeze passes through.",
  "A faint but distinct smell—lavender, brimstone, pine, or ozone—lingers in the air, coming and going unpredictably.",
  "Pressing an ear to any wall reveals soft murmurs that can’t be clearly understood.",
  "Strange symbols occasionally appear in corners or on floors, glowing faintly, then fading.",
  "Once a day, passersby see fleeting illusions of people or objects that aren’t actually there.",
  "Intricate topiaries around the structure move slowly during the day, rearranging themselves into new shapes every dawn.",
  "A grandfather clock or similar device keeps perfect time, and its ticking sounds oddly like a heartbeat.",
  "A single window—perhaps stained glass or crystal—appears to have been shattered but is locked in time as the shards twist and rattle.",
  "Each evening, a lantern hanging from a hook or post lights itself, then extinguishes at dawn.",
  "Clocks, sundials, or hourglasses in the area often run fast, slow, or backward without explanation.",
  "Visitors occasionally hear the distant sound of children or revelers laughing, though no one’s there.",
  "The wind, water, or flames here occasionally form a faint, whispering voice in Sylvan, Primordial, or another unusual tongue.",
  "One staircase leads to a door that is impossible to reach. No matter how far you run, walk, or fly, you never reach the top.",
  "Any existing portraits or paintings sometimes blink or shift expression when unobserved.",
  "A small patch of light always creates a rainbow on one wall or window, no matter the weather.",
  "Scrawlings in random places occasionally predict minor future events before fading away.",
  "A small torch, hearth, or brazier burns without fuel, providing warmth and abnormally colored light.",
  "Sudden extreme gusts of wind sometimes rush through corridors or halls, as if from an open window that doesn’t exist.",
  "A faint tackiness or magnetic cling covers interior surfaces, causing small items to cling unnaturally for a moment.",
  "Occasionally, muddy or dusty prints of unknown creatures appear, then vanish shortly after as if being washed away.",
  "Cups, spoons, or forks rattle softly at random intervals, as though unsettled by ghostly diners.",
  "Moss, mushrooms, or crystal formations grow upside-down from the ceiling.",
  "Hair and fur stand on end in certain spots, hinting at latent magical energies.",
  "Even without plumbing, one hears an occasional series of knocks and flowing liquid echoing within the walls or floors.",
  "One single door can speak in a whisper, offering cryptic comments or jokes when opened or closed.",
  "Loose floorboards constantly shift, hinting at hidden compartments or passages that keep relocating.",
  "Stonework or wallpaper rearranges itself subtly overnight, sometimes forming faces or words.",
  "One room or courtyard always appears in a different season. Even if indoors, it may rain or snow in the room; hirelings may need to rake leaves, etc.",
  "Subtle shimmers appear in the air in pastel hues, briefly tinting hair or clothes in faint rainbows.",
  "Puddles or pools that form in basins or low spots glow faintly at night.",
  "Sometimes when a door is opened, it briefly shows an illusion of another, faraway location before blinking back to normal.",
  "Metal objects give off a soft hum when touched, resonating like distant chimes. They may sometimes shock creatures that touch their surfaces.",
  "A tiny spiral of sparkling dust occasionally dances across rooms, producing high pitched chiming sounds.",
  "A low-hanging mist seeps through cracks at certain hours, making everything hazy for a short time.",
  "At odd intervals, the faint sound of pickaxes and distant chanting echoes from below ground (even if no mine exists).",
  "A broom or brush attempts to sweep by itself at night, leaving strange patterns on dusty floors.",
  "Tile or mosaic floors shift subtly over time, forming abstract images that reset by dawn.",
  "A small statue or figurine changes position or pose each morning, often appearing in surprising places.",
  "If cut away, ivy growing around the building regrows fully overnight, creeping even further inside.",
  "At random times, the clashing of swords or distant battle cries reverberate through halls.",
  "Doorframes occasionally sprout tiny blossoms that fall away when doors open, leaving behind a sweet aroma.",
  "Candles here never remain fully lit after only a few minutes; the candles are blown out even if no draft exists.",
  "Stepping on certain spots creates musical notes, forming a happy tune when walked in sequence.",
  "Water droplets form little jittering quartz-like crystals upon hitting the floor, dissolving after a few hours.",
  "Mirrors reflect details that aren’t in the room or show illusions of people who aren’t actually present.",
  "Stones or pebbles near the entrance rearrange themselves to form patterns or words at dawn.",
  "Anything said within the walls might be repeated back in an eerie whisper hours later.",
  "Faint, floating calligraphy appears at certain times, depicting cryptic phrases in unknown languages.",
  "Flowers near the bastion have mirrorlike petals that dazzle under sunlight or moonlight.",
  "A fountain or water source murmurs gentle, half-formed words when someone pauses to listen.",
  "Dust in sunbeams gathers into shapes resembling small animals or humanoid figures before dispersing.",
  "Touching certain walls triggers an echo of past conversations, laughter, or sobs.",
  "At night, thin veins of light trace across floors or beams, pulsing faintly like a heartbeat.",
  "Fine sparkles drift down in moonlight, as though stardust gently falling from the sky.",
  "The decor of the bastion magically morphs every day to represent some obscure holiday, even if there is a major holiday on the same day.",
  "The walls seem to gently expand and contract, as if the building itself sighs.",
  "During lightning storms or when shooting stars pass, faint runic symbols shimmer briefly on windows or glass.",
  "A friendly ghost, often seen tidying or humming around the base, then vanishing when spotted.",
  "A sprite-like creature has taken up residence, occasionally playing harmless pranks on inhabitants.",
  "Tiny shards of glowing crystal embed themselves into cracks, shifting color by mood or presence.",
  "Some gears or clockwork found on-site continue spinning without any power source.",
  "Translucent vines or flowers appear on walls at night, fading by sunrise.",
  "Threads of web sometimes appear and can’t easily be torn away, forming glimmering silver lines in certain corners.",
  "Ethereal birdlike shapes visit each morning, perching quietly on rafters or window sills, singing songs that sound like they’re played in reverse.",
  "Smoke or wind passing through a chimney forms into moving shapes in a sequence, as if retelling a story that it has overheard.",
  "Ash in the fireplace never diminishes; it resets every dawn, as if the fire never truly dies.",
  "A distant string instrument or flute can sometimes be heard, playing a melancholic tune with no visible musician.",
  "Placing a hand on certain walls leaves a glowing imprint that fades after about a minute.",
  "In dim light, a person moving quickly might leave a momentary afterimage behind.",
  "Crossing the main entrance at dawn or dusk elicits a soft, bell-like chord resonating through the bastion.",
  "Curtains, rugs, and tapestries subtly change color overnight, as though rewoven from the dreams of others.",
  "A small fountain or stream inside flows backward or upward, defying normal gravity.",
  "Moonlight passing through certain windows feels cold to the touch, creating small patches of frost on the sill or floor.",
  "Occasional white feathers float through the air, even if no birds are present. They dissolve into faint motes of light upon landing.",
  "Walls and floors waver in gentle ripples when someone daydreams or dozes off, returning to normal when they awaken.",
  "Tiny, harmless sparks of light occasionally rise from the floor or ground and vanish a few feet up, giving the place a flickering aura at dusk.",
  "At exactly one hour past midnight, a bell rings faintly three times—even if no bell is present.",
  "Puddles on the ground sometimes show a starry sky or other strange reflections even during the day.",
  "Unusually large and colorful moths gather in corners or around lamps, vanishing by morning.",
  "Carved metal or stone knockers occasionally speak, greet visitors, or demand passwords—even if no such password exists.",
  "Gusts around corners sound like old music box tunes, hauntingly sweet and slightly off-key.",
  "Certain spots cause all noise to vanish abruptly, as though stepping into a magical hush.",
  "Occasionally, a circular shimmer resembling a star-filled portal appears on a wall or floor—always ephemeral and vanishing in seconds without letting anything (or anyone) through.",
  "When multiple people breathe in unison within a room, a soft harmonic hum underlies their breathing, as if the building responds to their rhythm.",
  "If there’s stained glass, the figures or patterns depicted will sometimes change posture or shift color slightly between viewings.",
  "Plants (even potted ones) subtly turn to face creatures passing by, as if observing them.",
  "Any hearty laugh is answered by a faint echo of mirth, lingering in the rafters or upper floors.",
  "Interior surfaces shimmer as though dusted with tiny crystals or morning dew, yet remain dry to the touch.",
  "A single bell-like tone resonates through the halls at sunrise, lingering in the air for several seconds.",
  "If the ceiling is dark at night, faint star patterns slowly move across it, mirroring constellations that shift day to day.",
  "A separate area or courtyard hosts spectral flowers that wilt in daylight and bloom under moonlight."
];

